Repository hanaro-kiosk/mcdonald_kiosk_frontend, pull requests merged in 2024-05, with the labels that each got.

#12 [Feat/#4] 관리자 상품 관리
  src/App.tsx
  src/pages/AdminMenu/AdminMenuList/index.tsx
  src/pages/AdminMenu/AdminUpdateMenu/index.tsx
  src/pages/AdminMenu/index.tsx
  src/pages/AdminOutlet.tsx
  src/pages/MenuList/components/Button.tsx
  src/pages/MenuList/index.tsx
Labels: 기능구현, 퍼블리싱

#15 [Design/#13] 홈화면, 식사 장소 선택 화면, notfound 화면
  public/assets/potato.png
  public/assets/takeout.jpg
  src/App.css
  src/App.tsx
  src/pages/ChoicePlace.tsx
  src/pages/MenuList/index.tsx
  src/pages/NotFound.tsx
  src/pages/home.tsx
Labels: 퍼블리싱

#14 Feat/#5
  package-lock.json
  package.json
  src/App.tsx
  src/index.css
  src/pages/AdminOrder/component/OrderListItem.tsx
  src/pages/AdminOrder/component/Pagination.tsx
  src/pages/AdminOrder/index.tsx
  src/pages/AdminUpdateOrder/index.tsx
  yarn.lock
Labels: 기능구현

#17 refactor: btn onclick 수정, nickname 추가, admin 접근권한
  src/pages/AdminMenu/AdminMenuList/index.tsx
  src/pages/AdminMenu/AdminUpdateMenu/index.tsx
  src/pages/AdminMenu/index.tsx
  src/pages/AdminOrder/index.tsx
  src/pages/AdminOutlet.tsx
  src/pages/AdminUpdateOrder/index.tsx
  src/pages/AdminUser/index.tsx
  src/pages/AdminUserUpdate/index.tsx
  src/pages/MenuList/index.tsx
  src/pages/OrderComfirmation/index.tsx
  src/pages/OrderWithUserPoint/index.tsx
  src/pages/User/Login/index.tsx
  src/pages/home.tsx
Labels: 리팩토링
